// <auto-generated />
using System;
using ConsoleApp31.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp31.Migrations
{
    [DbContext(typeof(appdbcontext))]
    [Migration("20250315025117_createview")]
    partial class createview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleApp31.entities.course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("duration")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("topic_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("topic_id");

                    b.ToTable("course");
                });

            modelBuilder.Entity("ConsoleApp31.entities.department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("hirigdate")
                        .HasColumnType("int");

                    b.Property<int?>("ins_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ins_id")
                        .IsUnique()
                        .HasFilter("[ins_id] IS NOT NULL");

                    b.ToTable("department");
                });

            modelBuilder.Entity("ConsoleApp31.entities.instcourse", b =>
                {
                    b.Property<int>("ins_id")
                        .HasColumnType("int");

                    b.Property<int>("crs_id")
                        .HasColumnType("int");

                    b.Property<string>("evaluation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("instructorid")
                        .HasColumnType("int");

                    b.HasKey("ins_id", "crs_id");

                    b.HasIndex("instructorid");

                    b.ToTable("instcourse");
                });

            modelBuilder.Entity("ConsoleApp31.entities.instructor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("bouns")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<decimal>("hourrate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("workdeptid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("workdeptid");

                    b.ToTable("instructors");
                });

            modelBuilder.Entity("ConsoleApp31.entities.stcourse", b =>
                {
                    b.Property<int>("st_id")
                        .HasColumnType("int");

                    b.Property<int>("crs_id")
                        .HasColumnType("int");

                    b.Property<int?>("grade")
                        .HasColumnType("int");

                    b.Property<int?>("studentid")
                        .HasColumnType("int");

                    b.HasKey("st_id", "crs_id");

                    b.HasIndex("studentid");

                    b.ToTable("stcourse");
                });

            modelBuilder.Entity("ConsoleApp31.entities.student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int?>("dept_id")
                        .HasColumnType("int");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("dept_id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("ConsoleApp31.entities.topic", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("topic");
                });

            modelBuilder.Entity("ConsoleApp31.entities.course", b =>
                {
                    b.HasOne("ConsoleApp31.entities.topic", "topic")
                        .WithMany("course")
                        .HasForeignKey("topic_id");

                    b.Navigation("topic");
                });

            modelBuilder.Entity("ConsoleApp31.entities.department", b =>
                {
                    b.HasOne("ConsoleApp31.entities.instructor", "manager")
                        .WithOne("instructordept")
                        .HasForeignKey("ConsoleApp31.entities.department", "ins_id");

                    b.Navigation("manager");
                });

            modelBuilder.Entity("ConsoleApp31.entities.instcourse", b =>
                {
                    b.HasOne("ConsoleApp31.entities.instructor", null)
                        .WithMany("instructors")
                        .HasForeignKey("instructorid");
                });

            modelBuilder.Entity("ConsoleApp31.entities.instructor", b =>
                {
                    b.HasOne("ConsoleApp31.entities.department", "workdept")
                        .WithMany("instructors")
                        .HasForeignKey("workdeptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("workdept");
                });

            modelBuilder.Entity("ConsoleApp31.entities.stcourse", b =>
                {
                    b.HasOne("ConsoleApp31.entities.student", null)
                        .WithMany("stcourses")
                        .HasForeignKey("studentid");
                });

            modelBuilder.Entity("ConsoleApp31.entities.student", b =>
                {
                    b.HasOne("ConsoleApp31.entities.department", "department")
                        .WithMany("students")
                        .HasForeignKey("dept_id");

                    b.Navigation("department");
                });

            modelBuilder.Entity("ConsoleApp31.entities.department", b =>
                {
                    b.Navigation("instructors");

                    b.Navigation("students");
                });

            modelBuilder.Entity("ConsoleApp31.entities.instructor", b =>
                {
                    b.Navigation("instructordept")
                        .IsRequired();

                    b.Navigation("instructors");
                });

            modelBuilder.Entity("ConsoleApp31.entities.student", b =>
                {
                    b.Navigation("stcourses");
                });

            modelBuilder.Entity("ConsoleApp31.entities.topic", b =>
                {
                    b.Navigation("course");
                });
#pragma warning restore 612, 618
        }
    }
}
